version: "3"

networks:
  elastic-net:
    driver: bridge
    
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - ./storage/elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-net